### ISSUE TITLE
Reference (use) results of previous sub-request in further sub-requests of the batch request

### ISSUE THREAD

**Issue by ernestas2k** [dtkav/flask-batch#1]
Would you consider anything like that? The idea is helpful when you have a real life scenario, let's say create an object, then create two more settings or children objects and want to attach them, and do it all in batch.

One of options that come into my mind is (in pseudo):

```
{
   (1) create parent object -> {'name': 'parent1'},
   (2) create child -> {'name': 'child1', 'parentId': '@[1].id'} (random syntax, we expect that result of first request will contain json field 'id' and server will allow to use it for subsequent sub-requests)
}
```

Would like to hear your opinion or alternative approaches.

**Comment by dtkav** [comment]
Her there @ernestas2k - sorry for not getting back to you. I forgot to follow my own repo!

A good way to do this is to use client-generated UUIDs, and replace POST methods with PUT.
This way, the client knows the ids in advance when creating objects, and can coordinate them.

So it might look something like
```
PUT /api/parent/<uuid1>/ {"some": "fields"}
PUT /api/child/<uuid2>/  {"parent_id": <uuid1>}
PUT /api/child/<uuid3>/ {"parent_id": <uuid1>}
```

Unlike POST, PUT is idempotent which is really nice if you need to retry any failed transmissions.
